# Generated by Django 5.0.1 on 2024-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
