# Generated by Django 5.0.1 on 2024-02-25 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0003_alter_familyuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='datatypes.family'),
            preserve_default=False,
        ),
    ]
