# Generated by Django 5.0.1 on 2024-02-25 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0004_familymember_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='children',
            field=models.ManyToManyField(blank=True, default=None, to='datatypes.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='father',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_father', to='datatypes.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='mother',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_mother', to='datatypes.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_spouse', to='datatypes.familymember'),
        ),
    ]
